### ISSUE TITLE
如果同步的文件大小超过150MB的，报错

### ISSUE THREAD

**Issue by cong5** [mehwww/oss-sync#1]
``` javascript
child_process.js:958
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at Git.exec (/usr/local/node/lib/node_modules/oss-sync/lib/git.js:18:3)
    at Git.commit (/usr/local/node/lib/node_modules/oss-sync/lib/git.js:37:84)
    at /usr/local/node/lib/node_modules/oss-sync/sync.js:92:12
    at fn (/usr/local/node/lib/node_modules/oss-sync/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/node/lib/node_modules/oss-sync/node_modules/async/lib/async.js:557:34)
```

**Comment by mehwww** [comment]
我这边测试倒是没什么问题，看报错信息似乎是内存不足，能详细说说吗

**Comment by mehwww** [comment]
修复了可能存在的内存不足的问题，升级到0.1.2再试下看看

**Comment by cong5** [comment]
嗯，谢谢。我更新试试

**Comment by cong5** [comment]
更新到0.1.2了，还是包这个错误。
你使用的nodejs是什么版本的？
以下是我的服务器上安装的nodejs和oss-sync的版本

``` shell
[root@abcdefg~]# /usr/local/node/bin/osync /data/bash/website_backup.json

child_process.js:958
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at Git.exec (/usr/local/node/lib/node_modules/oss-sync/lib/git.js:18:3)
    at Git.commit (/usr/local/node/lib/node_modules/oss-sync/lib/git.js:37:84)
    at /usr/local/node/lib/node_modules/oss-sync/lib/sync.js:92:12
    at fn (/usr/local/node/lib/node_modules/oss-sync/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/node/lib/node_modules/oss-sync/node_modules/async/lib/async.js:557:34)
[root@abcdefg~]# /usr/local/node/bin/osync --version
0.1.2
[root@abcdefg~]# node -v
v0.10.35
```

**Comment by mehwww** [comment]
应该不是版本的问题，之前只是准备给图片之类的小文件用的，现在用Promise重构了代码，麻烦升级到0.2.0再试试

**Comment by cong5** [comment]
Nice~
Success~
谢谢~，成功了，现在上传可以显示进度条，同时不会报错了
