### ISSUE TITLE
当我升级到0.6.3后，报错SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by maskxu** [mehwww/oss-sync#14]
/usr/lib/node_modules/oss-sync/lib/sync.js:3
const fs = require('fs')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/oss-sync/bin/osync.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

当我注释掉  'use strict' 后又有其他语法错误。我对nodejs 不是很熟悉。是不是我nodejs的环境问题？我的node版本为 v0.10.36

**Comment by mehwww** [comment]
因为用了些 ES2015 的语法，请至少使用 node 4.x 以上版本

**Comment by maskxu** [comment]
thank you
